# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/d_mcs/d_mcs.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_mcs || ORIG_REF_NAME==d_mcs}]

# IP: bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_mcs_microblaze_mcs_0_0 || ORIG_REF_NAME==d_mcs_microblaze_mcs_0_0}]

# XDC: bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_mcs_microblaze_mcs_0_0 || ORIG_REF_NAME==d_mcs_microblaze_mcs_0_0}] {/U0 }]/U0 ]]

# XDC: bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_mcs_microblaze_mcs_0_0 || ORIG_REF_NAME==d_mcs_microblaze_mcs_0_0}] {/U0 }]/U0 ]]

# XDC: bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0_ooc.xdc

# XDC: bd/d_mcs/d_mcs_ooc.xdc
