webtalk_init -webtalk_dir Z:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\02_MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 17 05:26:15 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "n3g9psqcf12i8tf3qrq53vbv17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1500040555881" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key hwid -value "1498602404042" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key bspid -value "1498602437821" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1500040555881"
webtalk_add_data -client sdk -key uid -value "1500283137122" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key Device -value "xc7k410t" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key IsHandoff -value "false" -context "sdk\\\\hardware/1500283137122"
webtalk_add_data -client sdk -key uid -value "1500283239935" -context "sdk\\\\bsp/1500283239935"
webtalk_add_data -client sdk -key hwid -value "1500283137122" -context "sdk\\\\bsp/1500283239935"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1500283239935"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1500283239935"
webtalk_transmit -clientid 2357120394 -regid "" -xml Z:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\02_MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html Z:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\02_MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm Z:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\02_MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus\\MicroBlaze_Mcs_IO_Bus.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
