# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k410tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.cache/wt [current_project]
set_property parent.project_path G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.sdk/gpio_rw/Debug/gpio_rw.elf
set_property SCOPED_TO_REF d_mcs [get_files -all G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.sdk/gpio_rw/Debug/gpio_rw.elf]
set_property SCOPED_TO_CELLS microblaze_mcs_0/U0/microblaze_I [get_files -all G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.sdk/gpio_rw/Debug/gpio_rw.elf]
add_files G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/d_mcs.bd
set_property used_in_implementation false [get_files -all g:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/ip/d_mcs_microblaze_mcs_0_0/d_mcs_microblaze_mcs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/d_mcs_ooc.xdc]
set_property is_locked true [get_files G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/d_mcs.bd]

read_vhdl -library xil_defaultlib G:/work/git/LabVIEW_Fpga/05_MicroBlaze_Mcs/01_MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO/MicroBlaze_Mcs_GPIO.srcs/sources_1/bd/d_mcs/hdl/d_mcs_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top d_mcs_wrapper -part xc7k410tffg900-2
write_checkpoint -noxdef d_mcs_wrapper.dcp
catch { report_utilization -file d_mcs_wrapper_utilization_synth.rpt -pb d_mcs_wrapper_utilization_synth.pb }
