# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k410tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/VivadoProject/AXI_Stream.cache/wt [current_project]
set_property parent.project_path Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/VivadoProject/AXI_Stream.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set src_rc [catch { 
  puts "source Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PreSynthesize.tcl"
  source Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PreSynthesize.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PreSynthesize.tcl failed"
  return -code error
}
add_files -quiet Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/checkpoint_2.dcp
set_property used_in_implementation false [get_files Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/checkpoint_2.dcp]
read_vhdl -library xil_defaultlib {
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiUtilities.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgCommIntConfiguration.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlop.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlopFallingEdge.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgCommunicationInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlopBool.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlopBoolFallingEdge.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncAsyncInBase.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgGray.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiDmaConfig.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiDmaRegMap.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PulseSyncBase.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlopGray.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DFlopSlvResetVal.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncBase.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaPulseSyncBaseWrapper.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaSimpleDualPortRAM_ByteEnable.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiDma.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgOneHot.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PulseSyncBool.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/ResetSync.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSimpleDualPortRAM_ByteEnable.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortFifoPtrClockCrossing.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortFifoSyncGrayCounters.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncBool.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/HandshakeBaseResetCross.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaFifoPortReset.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgByteArray.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcMasterPort.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortDataPackingFifo.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortInStrmDPRAM.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortInStrmFifoFlags.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortOutStrmDPRAM.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortOutStrmFifoFlags.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/HandshakeBase.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaFifoClearControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaFlipFlopFifo.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcStreamStates.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommunicationInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiFpgaFifo.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TimeoutManager.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcComponentEnableChain.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcComponentInputStateHolder.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcComponentOutputStateHolder.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcComponentStateTransitionEnableChain.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcComponentStreamStateEnableChain.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortInStrmFifo.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortOutStrmFifo.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncSlAsyncIn.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/HandshakeSLV.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/HandshakeSLV_Ack.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaFifoCountControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaFifoPopBuffer.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortDmaFifos.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/d_microblaze_wrapper_top.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcInputFifoInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcOutputFifoInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncBoolAsyncIn.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncSL.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcArbiter.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcInputDataControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcRegs.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiFpgaIrqRegisters.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TimedLoopController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TimedLoopDomainCrosser.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/d_microblaze_wrapper_topNiFpgaAG_00000003_CustomNode.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcFifos.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcInputController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcLvFpgaIrq.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcOutputController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcRegisters.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSinkStreamDataReceiver.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSinkStreamStateController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSinkStreamTcrUpdateController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSourceStreamStateController.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortInputDataToDmaDelay.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortStrmArbiterRoundRobin.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DoubleSyncSLV.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaHostAccessibleRegister.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaLocalResHolderRead.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaLocalResHolderWrite.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaRegFrameworkShiftReg.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgChinch.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortCommIfcMasterPortFlatTypes.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortDmaFifosFlatTypes.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgFpgaDeviceSpecs.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgNiFpgaViControlRegister.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgRegister.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/SafeBusCrossing.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TimedLoopCore.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/XDataNode.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/XDataNodeOut.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/bushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForAXI_STR_RXD_tdata_ctl_8RHFpgaReadPortOnResbushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForAXI_STR_RXD_tlast_ctl_9RHFpgaReadPortOnResbushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForAXI_STR_RXD_tvalid_ctl_10RHFpgaReadPortOnResbushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForAXI_STR_TXD_tready_ctl_7RHFpgaReadPortOnResbushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForMiteIoLikePortOnResInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForsys_reset_ctl_11RHFpgaReadPortOnResbushold.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/CustomArbForTopEnablesPortOnResTopEnablePassThru.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DiagramReset.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcInputArbiter.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcInputDataControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcInputStream.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcIrqInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcMasterReadInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcMasterWriteInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcOutputArbiter.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcOutputStream.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSinkDataControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommIfcSinkStream.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/Interface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/InvisibleResholder.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaAG_00000001_TimedLoopDiagram.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaAG_TimedLoopControllerContainer_18.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaClockManagerControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaCtrlIndRegister.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgChinchConfig.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgPXIe659XR_PoscDebug.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TopEnablePassThru.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/ViControl.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/ViSignature.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortFixedDmaCommunicationInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaAG_Fpga_dash_AXI_dash_Stream_dash_Test_2.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaMmcmWrapper.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgGenericConfigPort.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgPosc.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgPXIe6592R_BoardDevices.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgPXIe659XR_BoardDevices.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/WrapBufg.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DmaPortCommunicationInterface.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/DramInitDoneCorrection.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/NiFpgaDmaPortIfcPipeline.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgDmaPortRecordFlattening.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgExportRevision.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgGenericConfigPortConfig.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PkgPXIe6592R_PoscROM.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe659XR_PoscROM.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIeK7TimingEngine.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/Sync100Capture.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/TheWindow.vhd
  Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe6592R_Top_Gen2x8.vhd
}
read_edif Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/G2X8ChinchWithDmaPortBim128.edf
read_edif Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe6592R_FixedLogic.edf
read_edif Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe659XR_DRAM.edf
read_xdc Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe6592R_Top_Gen2x8.xdc
set_property used_in_implementation false [get_files Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/03_MicroBlaze_AXI_Stream/ProjectExportForVivado/AXI_Stream/NIProtectedFiles/PXIe6592R_Top_Gen2x8.xdc]

synth_design -top PXIe6592R_Top_Gen2x8 -part xc7k410tffg900-2 -flatten_hierarchy full -keep_equivalent_registers
write_checkpoint -noxdef PXIe6592R_Top_Gen2x8.dcp
catch { report_utilization -file PXIe6592R_Top_Gen2x8_utilization_synth.rpt -pb PXIe6592R_Top_Gen2x8_utilization_synth.pb }
