# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k410tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.cache/wt [current_project]
set_property parent.project_path Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.sdk/lwip_test1/Debug/lwip_test1.elf
set_property SCOPED_TO_REF d_microblaze [get_files -all Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.sdk/lwip_test1/Debug/lwip_test1.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.sdk/lwip_test1/Debug/lwip_test1.elf]
add_files Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/d_microblaze.bd
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_dlmb_v10_0/d_microblaze_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_dlmb_v10_0/d_microblaze_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_ilmb_v10_0/d_microblaze_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_ilmb_v10_0/d_microblaze_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_dlmb_bram_if_cntlr_0/d_microblaze_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_ilmb_bram_if_cntlr_0/d_microblaze_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_lmb_bram_0/d_microblaze_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_mdm_1_0/d_microblaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_mdm_1_0/d_microblaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_0_0/d_microblaze_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_1_0/d_microblaze_axi_fifo_mm_s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_blk_mem_gen_0_0/d_microblaze_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_xbar_0/d_microblaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_bram_ctrl_0_0/d_microblaze_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_0/d_microblaze_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_1/d_microblaze_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_2/d_microblaze_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_3/d_microblaze_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_4/d_microblaze_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/ip/d_microblaze_auto_pc_5/d_microblaze_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/d_microblaze_ooc.xdc]
set_property is_locked true [get_files Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/d_microblaze.bd]

read_vhdl -library xil_defaultlib Z:/work/git/LabVIEW_Fpga/06_MicroBlaze/04_MicroBlaze_lwIP/MicroBlaze_lwIP/MicroBlaze_lwIP.srcs/sources_1/bd/d_microblaze/hdl/d_microblaze_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top d_microblaze_wrapper -part xc7k410tffg900-2
write_checkpoint -noxdef d_microblaze_wrapper.dcp
catch { report_utilization -file d_microblaze_wrapper_utilization_synth.rpt -pb d_microblaze_wrapper_utilization_synth.pb }
