# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/d_microblaze/d_microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze || ORIG_REF_NAME==d_microblaze}]

# IP: bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_0}]

# IP: bd/d_microblaze/ip/d_microblaze_dlmb_v10_0/d_microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_dlmb_v10_0 || ORIG_REF_NAME==d_microblaze_dlmb_v10_0}]

# IP: bd/d_microblaze/ip/d_microblaze_ilmb_v10_0/d_microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_ilmb_v10_0 || ORIG_REF_NAME==d_microblaze_ilmb_v10_0}]

# IP: bd/d_microblaze/ip/d_microblaze_dlmb_bram_if_cntlr_0/d_microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==d_microblaze_dlmb_bram_if_cntlr_0}]

# IP: bd/d_microblaze/ip/d_microblaze_ilmb_bram_if_cntlr_0/d_microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==d_microblaze_ilmb_bram_if_cntlr_0}]

# IP: bd/d_microblaze/ip/d_microblaze_lmb_bram_0/d_microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_lmb_bram_0 || ORIG_REF_NAME==d_microblaze_lmb_bram_0}]

# IP: bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_periph_0/d_microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_axi_periph_0}]

# IP: bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_axi_intc_0}]

# IP: bd/d_microblaze/ip/d_microblaze_microblaze_0_xlconcat_0/d_microblaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_xlconcat_0}]

# IP: bd/d_microblaze/ip/d_microblaze_mdm_1_0/d_microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_mdm_1_0 || ORIG_REF_NAME==d_microblaze_mdm_1_0}]

# IP: bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_clk_wiz_1_0 || ORIG_REF_NAME==d_microblaze_clk_wiz_1_0}]

# IP: bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0}]

# IP: bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_0_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_0_0}]

# IP: bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_0_0/d_microblaze_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==d_microblaze_axi_fifo_mm_s_0_0}]

# IP: bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_1_0/d_microblaze_axi_fifo_mm_s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==d_microblaze_axi_fifo_mm_s_1_0}]

# IP: bd/d_microblaze/ip/d_microblaze_blk_mem_gen_0_0/d_microblaze_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_blk_mem_gen_0_0 || ORIG_REF_NAME==d_microblaze_blk_mem_gen_0_0}]

# IP: bd/d_microblaze/ip/d_microblaze_xbar_0/d_microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_xbar_0 || ORIG_REF_NAME==d_microblaze_xbar_0}]

# IP: bd/d_microblaze/ip/d_microblaze_axi_bram_ctrl_0_0/d_microblaze_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_axi_bram_ctrl_0_0 || ORIG_REF_NAME==d_microblaze_axi_bram_ctrl_0_0}]

# IP: bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_1_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_1_0}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_0/d_microblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_0 || ORIG_REF_NAME==d_microblaze_auto_pc_0}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_1/d_microblaze_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_1 || ORIG_REF_NAME==d_microblaze_auto_pc_1}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_2/d_microblaze_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_2 || ORIG_REF_NAME==d_microblaze_auto_pc_2}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_3/d_microblaze_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_3 || ORIG_REF_NAME==d_microblaze_auto_pc_3}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_4/d_microblaze_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_4 || ORIG_REF_NAME==d_microblaze_auto_pc_4}]

# IP: bd/d_microblaze/ip/d_microblaze_auto_pc_5/d_microblaze_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_auto_pc_5 || ORIG_REF_NAME==d_microblaze_auto_pc_5}]

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0_ooc_debug.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_0/d_microblaze_microblaze_0_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_dlmb_v10_0/d_microblaze_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_dlmb_v10_0 || ORIG_REF_NAME==d_microblaze_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_dlmb_v10_0/d_microblaze_dlmb_v10_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_ilmb_v10_0/d_microblaze_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_ilmb_v10_0 || ORIG_REF_NAME==d_microblaze_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_ilmb_v10_0/d_microblaze_ilmb_v10_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_dlmb_bram_if_cntlr_0/d_microblaze_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_ilmb_bram_if_cntlr_0/d_microblaze_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_lmb_bram_0/d_microblaze_lmb_bram_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==d_microblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_microblaze_0_axi_intc_0/d_microblaze_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_mdm_1_0/d_microblaze_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_mdm_1_0 || ORIG_REF_NAME==d_microblaze_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_mdm_1_0/d_microblaze_mdm_1_0_ooc_trace.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_clk_wiz_1_0 || ORIG_REF_NAME==d_microblaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_clk_wiz_1_0 || ORIG_REF_NAME==d_microblaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/d_microblaze/ip/d_microblaze_clk_wiz_1_0/d_microblaze_clk_wiz_1_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0}]

# XDC: bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==d_microblaze_rst_clk_wiz_1_100M_0}]

# XDC: bd/d_microblaze/ip/d_microblaze_rst_clk_wiz_1_100M_0/d_microblaze_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_0_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_0_0/d_microblaze_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_0_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_0_0/d_microblaze_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_fifo_mm_s_1_0/d_microblaze_axi_fifo_mm_s_1_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_blk_mem_gen_0_0/d_microblaze_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_xbar_0/d_microblaze_xbar_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_bram_ctrl_0_0/d_microblaze_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_1_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_axi_gpio_1_0/d_microblaze_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==d_microblaze_axi_gpio_1_0 || ORIG_REF_NAME==d_microblaze_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_0/d_microblaze_auto_pc_0_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_1/d_microblaze_auto_pc_1_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_2/d_microblaze_auto_pc_2_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_3/d_microblaze_auto_pc_3_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_4/d_microblaze_auto_pc_4_ooc.xdc

# XDC: bd/d_microblaze/ip/d_microblaze_auto_pc_5/d_microblaze_auto_pc_5_ooc.xdc

# XDC: bd/d_microblaze/d_microblaze_ooc.xdc
