webtalk_init -webtalk_dir G:\\work\\git\\LabVIEW_Fpga\\06_MicroBlaze\\01_MicroBlaze_GPIO\\MicroBlaze_GPIO\\MicroBlaze_GPIO.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun 23 19:47:17 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "72bam497pvca34i24o9rqd7d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1498261094602" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4_AR67478_AR66782_AR66772_AR66092_AR65813_ar68397_cr964221_2015_4" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key Device -value "7k410t" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1498261094602"
webtalk_add_data -client sdk -key uid -value "1498261241875" -context "sdk\\\\bsp/1498261241875"
webtalk_add_data -client sdk -key hwid -value "1498261094602" -context "sdk\\\\bsp/1498261241875"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1498261241875"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1498261241875"
webtalk_add_data -client sdk -key uid -value "1498261244003" -context "sdk\\\\application/1498261244003"
webtalk_add_data -client sdk -key hwid -value "1498261094602" -context "sdk\\\\application/1498261244003"
webtalk_add_data -client sdk -key bspid -value "1498261241875" -context "sdk\\\\application/1498261244003"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1498261244003"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1498261244003"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1498261244003"
webtalk_transmit -clientid 890884546 -regid "" -xml G:\\work\\git\\LabVIEW_Fpga\\06_MicroBlaze\\01_MicroBlaze_GPIO\\MicroBlaze_GPIO\\MicroBlaze_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html G:\\work\\git\\LabVIEW_Fpga\\06_MicroBlaze\\01_MicroBlaze_GPIO\\MicroBlaze_GPIO\\MicroBlaze_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm G:\\work\\git\\LabVIEW_Fpga\\06_MicroBlaze\\01_MicroBlaze_GPIO\\MicroBlaze_GPIO\\MicroBlaze_GPIO.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
