webtalk_init -webtalk_dir G:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\01_MicroBlaze_GPIO\\MicroBlaze_Mcs_GPIO\\MicroBlaze_Mcs_GPIO.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 17 22:57:05 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hj1ejc8t01cfv1fj7btkf9ls2o" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1497725668240" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key Device -value "xc7k410t" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key IsHandoff -value "false" -context "sdk\\\\hardware/1497725668240"
webtalk_add_data -client sdk -key uid -value "1497725783250" -context "sdk\\\\bsp/1497725783250"
webtalk_add_data -client sdk -key hwid -value "1497725668240" -context "sdk\\\\bsp/1497725783250"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1497725783250"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1497725783250"
webtalk_add_data -client sdk -key uid -value "1497725786406" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key hwid -value "1497725668240" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key bspid -value "1497725783250" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1497725786406"
webtalk_add_data -client sdk -key uid -value "1497726183900" -context "sdk\\\\bsp/1497726183900"
webtalk_add_data -client sdk -key hwid -value "1497725668240" -context "sdk\\\\bsp/1497726183900"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1497726183900"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1497726183900"
webtalk_add_data -client sdk -key uid -value "1497726186282" -context "sdk\\\\application/1497726186282"
webtalk_add_data -client sdk -key hwid -value "1497725668240" -context "sdk\\\\application/1497726186282"
webtalk_add_data -client sdk -key bspid -value "1497726183900" -context "sdk\\\\application/1497726186282"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1497726186282"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1497726186282"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1497726186282"
webtalk_transmit -clientid 1977754893 -regid "" -xml G:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\01_MicroBlaze_GPIO\\MicroBlaze_Mcs_GPIO\\MicroBlaze_Mcs_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html G:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\01_MicroBlaze_GPIO\\MicroBlaze_Mcs_GPIO\\MicroBlaze_Mcs_GPIO.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm G:\\work\\git\\LabVIEW_Fpga\\05_MicroBlaze_Mcs\\01_MicroBlaze_GPIO\\MicroBlaze_Mcs_GPIO\\MicroBlaze_Mcs_GPIO.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
